// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "uz":
            case "babey":return img`
...................
....fffffffff......
...f1ddddddd1f.....
..f11111111111f....
..fdfcccccccfdf....
..fdcfffffffcdf....
..fdc6fffff6cdf....
..fdc6fffff6cdf....
..fdc6fffff6cdf....
..fdcfff6fffcdf....
..fdcccccccccdf....
..cfffffffffffc....
...cfcccccccfc.....
..ccc111141bccc5.5.
..fdcdd1118dcdfccc.
..ffcdddddddcffccc.
.....cfffffcc...c..
.....cdc.cdc.ccc...
.....ccc.ccc.......
`;
            case "image1":
            case "babeyBackup":return img`
...................
....fffffffff......
...f1ddddddd1f.....
..f11111111111f....
..fdfcccccccfdf....
..fdcfffffffcdf....
..fdc6fffff6cdf....
..fdc6fffff6cdf....
..fdc6fffff6cdf....
..fdcfff6fffcdf....
..fdcccccccccdf....
..cfffffffffffc....
...cfcccccccfc.....
..ccc111141bccc5.5.
..fdcdd1118dcdfccc.
..ffcdddddddcffccc.
.....cfffffcc...c..
.....cdc.cdc.ccc...
.....ccc.ccc.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
